image: node:latest

stages:
  - development
  - production

development:
  type: deploy
  stage: production
  before_script:
    - npm i .
    - npm run test
    - npm run instrument
  script:
    - npm run dev
  after_script:
    - npm run report-cover
  only:
    - master

production:
  type: deploy
  stage: production
  before_script:
    - npm i .
    - npm run test
    - npm run instrument
  script:
    - npm run build
    - node __sapper__/build
  after_script:
    - npm run report-cover
  only:
    - master
